# Generated by Django 5.2.7 on 2025-10-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('sysadmin', 'System Administrator'), ('student', 'Student'), ('dean_of_students', 'Dean of Students'), ('finance_director', 'Finance Director'), ('academic_registrar', 'Academic Registrar'), ('head_of_department', 'Head of Department'), ('faculty_dean', 'Faculty Dean'), ('medical_officer', 'Medical Officer'), ('nche_officer', 'NCHE Officer'), ('lecturer', 'Lecturer')], max_length=20),
        ),
    ]
