# Generated by Django 5.2.8 on 2025-12-08 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_guardian_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_guardian_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
