# Generated by Django 5.2.8 on 2025-12-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_book', '0002_alter_student_parent_guardian_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessnumber',
            name='access_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='static_access_number',
            field=models.CharField(blank=True, help_text='Format: PROGRAM-XXX (e.g., 909-A001)', max_length=15, unique=True),
        ),
    ]
