# Generated by Django 5.2.8 on 2025-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_book', '0003_alter_accessnumber_access_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(help_text='Manual registration number (e.g., 909/24D/U/A001)', max_length=50, unique=True),
        ),
    ]
