# Generated by Django 5.2.8 on 2025-12-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_book', '0004_alter_student_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_number']},
        ),
        migrations.AlterField(
            model_name='student',
            name='static_access_number',
            field=models.CharField(blank=True, help_text='Format: PROGRAM-XXXX (e.g., 909-AA01)', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_number',
            field=models.CharField(blank=True, help_text='Sequential code like AA01', max_length=10),
        ),
    ]
