"""
Django settings for AttendanceSystem project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f6pf1tm#rtb&bl@1g+w-ggcqf_7a3fn8wtg#c2q83h@6znkej1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '10.32.168.19',
    '192.168.1.13',      # Your local network IP
    '192.168.43.57',     # Network IP accessible across internet
    '102.34.17.131',     # Your external/public IP
    '41.210.146.137',    # Current public IP
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    "storages",
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',

    'accounts',
    'attendance_ai',
    'attendance_sms',
    'pass_book',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AttendanceSystem.urls'
'''
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
'''

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # This line is crucial
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'AttendanceSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

'''
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'postgres'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'mysecretpassword'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# In your settings.py file
AUTH_USER_MODEL = 'accounts.User'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Remove these individual MinIO settings:
# MINIO_ACCESS_KEY = os.environ.get('MINIO_ACCESS_KEY', 'minioadmin')
# MINIO_SECRET_KEY = os.environ.get('MINIO_SECRET_KEY', 'minioadmin')
# MINIO_ENDPOINT = os.environ.get('MINIO_ENDPOINT', 'http://localhost:9000')
# MINIO_STORAGE_BUCKET_NAME = os.environ.get('MINIO_BUCKET_NAME', 'django-storage')

'''

# Minio/S3 Storage Configuration
AWS_ACCESS_KEY_ID = "minioadmin"
AWS_SECRET_ACCESS_KEY = "minioadmin"
AWS_STORAGE_BUCKET_NAME = "django-storage"
AWS_S3_ENDPOINT_URL = "http://localhost:9000"
AWS_S3_ENDPOINT_URL = "http://minio:9000"  # Internal endpoint for Docker containers
AWS_S3_CUSTOM_DOMAIN = "192.168.1.13:9000"
AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = False  # Disable SSL verification for local development

# Storage backends configuration
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": "django-static",
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "location": "static",  # Subdirectory within the bucket
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
        },
    },
}

# Alternative: If you want to use the global AWS settings with STORAGES
# You can also configure it this way (simpler, uses global settings):
"""
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": "django-static",
            "location": "static",
        },
    },
}
"""







'''

'''

# Keep only these - they're what django-storages actually uses:
AWS_ACCESS_KEY_ID = "minioadmin"
AWS_SECRET_ACCESS_KEY = "minioadmin" 
AWS_STORAGE_BUCKET_NAME = "django-storage"
AWS_S3_ENDPOINT_URL = "http://localhost:9000"
#AWS_S3_ENDPOINT_URL = 'http://minio:9000'  # Internal endpoint for Django to connect
AWS_S3_CUSTOM_DOMAIN = '192.168.1.13:9000'  #
AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = False
STORAGES = {
"default": {
"BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
"staticfiles": {
"BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
"OPTIONS": {
"bucket_name": "django-static",
"location": "static",
        },
    },
} i want those links to be compartible with these allowed hosts 
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.1.13',      # Your local network IP
    '102.34.17.131',     # Your external/public IP
]

'''




















'''

# Keep only these - they're what django-storages actually uses:
AWS_ACCESS_KEY_ID = "minioadmin"
AWS_SECRET_ACCESS_KEY = "minioadmin" 
AWS_STORAGE_BUCKET_NAME = "django-storage"
AWS_S3_ENDPOINT_URL = "http://localhost:9000"
AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": "django-static",
            "location": "static",
        },
    },
}
'''
'''
import os

# Minio/S3 Storage Configuration
AWS_ACCESS_KEY_ID = "minioadmin"
AWS_SECRET_ACCESS_KEY = "minioadmin"
AWS_STORAGE_BUCKET_NAME = "django-storage"

# Determine if running in Docker
IS_DOCKER = os.environ.get('DOCKER_ENV', 'false').lower() == 'true'

# Use appropriate endpoint based on environment
if IS_DOCKER:
    # Inside Docker: use service name
    AWS_S3_ENDPOINT_URL = "http://minio:9000"
else:
    # Outside Docker: use localhost
    AWS_S3_ENDPOINT_URL = "http://localhost:9000"

# For browser access - this is what gets served in HTML
# Use your local network IP so images work from any device
AWS_S3_CUSTOM_DOMAIN = "192.168.1.13:9000/django-storage"

AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = False
AWS_QUERYSTRING_AUTH = False  # Important: Makes URLs public
AWS_S3_USE_SSL = False  # No SSL for local development

# Storage backends configuration
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "use_ssl": AWS_S3_USE_SSL,
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
        },
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": AWS_ACCESS_KEY_ID,
            "secret_key": AWS_SECRET_ACCESS_KEY,
            "bucket_name": "django-static",
            "endpoint_url": AWS_S3_ENDPOINT_URL,
            "custom_domain": "192.168.1.13:9000/django-static",
            "location": "static",
            "file_overwrite": AWS_S3_FILE_OVERWRITE,
            "querystring_auth": AWS_QUERYSTRING_AUTH,
            "use_ssl": AWS_S3_USE_SSL,
        },
    },
}
'''


'''
# Keep only these - they're what django-storages actually uses:
AWS_ACCESS_KEY_ID = "minioadmin"
AWS_SECRET_ACCESS_KEY = "minioadmin" 
AWS_STORAGE_BUCKET_NAME = "django-storage"
AWS_S3_ENDPOINT_URL = "http://localhost:9000"
AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = False

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": "django-static",
            "location": "static",
        },
    },
}
'''

# Keep only these - they're what django-storages actually uses:
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', 'minioadmin')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', 'minioadmin')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', 'django-storage')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', 'http://localhost:9000')
AWS_S3_FILE_OVERWRITE = False
AWS_S3_VERIFY = False

# Add these for better MinIO compatibility:
AWS_S3_ADDRESSING_STYLE = "path"  # Important for MinIO
AWS_S3_USE_SSL = False  # If using HTTP, not HTTPS
AWS_QUERYSTRING_AUTH = False  # Optional: for public files without signed URLs

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "bucket_name": "django-static",
            "location": "static",
        },
    },
}

# Optional: If you want to serve static/media files directly from MinIO
#AWS_S3_CUSTOM_DOMAIN = "10.32.168.19:9000"  # Optional: for direct file access